### PR TITLE
Fix workflow.yml.template

### PR DESCRIPTION
**Pull request by geeeger**
fix run npm command error😀

### CODE REVIEW

**Comment by GaryB432** [comment]
thank you

**Comment by geeeger** [comment]
> thank you

it's nice to use,this template is very nice👍

**Comment by GaryB432** [comment]
What are you building with it?

**Comment by geeeger** [comment]
[https://github.com/geeeger-pkgs/utils](https://github.com/geeeger-pkgs/utils)

just some private packages

**Pull request merged**
